### ISSUE TITLE
QUICK_VETO, hvac_modes

### ISSUE THREAD

**Issue by Tomasonx** [thomasgermain/pymultiMATIC#10]
Can you add to climate.vaillant_xxx on [hvac_modes: off,auto,heat] to have a 4th possibility maybe "Rest"?

If in the room are 20 degrees:
	- when you change the temperature QUICK_VETO from 20 to 22 the hvac_modes will be Heat = OK
	- when you change the temperature QUICK_VETO from 20 to 10 degrees the hvac_modes will be also Heat, but must be something like Rest, because you do not heat the room

**Comment by thomasgermain** [comment]
Yeah, this is still in progress. I can check if the target temp of the quick_veto is under the actual room temperature. But since temperature is 0.1 accurate so you may go to heat, rest, heat, rest, etc.

There is no way to know the room is actually heating, except checking current temperature and target temperature. And i'm not even sure it will work: if your room is 25 and you set a quick veto to 25.5, i'm not sure heating will go on.

I'm still thinking about a solution

**Comment by Tomasonx** [comment]
On how I see it you must change only one thing.


If the target temperature is smaller than room temperature you have "rest" not "heat".
And what the boiler will do, it is another story.

I am glad that you think about a solution.

**Comment by thomasgermain** [comment]
So, I eventually had a look, sorry for the delay.

First, i'm tight to HA API for the hvac_modes. The only option I have for `rest` is actually `off`. Doc says: `All activity disabled / Device is off/standby`

So basically, if you set a quick veto (or manual mode) with a target temperature under the current temperature, the hvac_mode will be off.

What do you think ?

**Comment by Tomasonx** [comment]
If you ask me this is not a good solution.
Already Vaillant has implemented total wrong Off mode.


For me a solution will be...

you have hvac_modes: heat,off,auto
and you display this like Heat,Off,Auto

You can not change hvac_modes: heat,off,auto, but you can change (I think) Heat => abcd.

If you can do that, when you will have (hvac_modes = heat) you can display Heat if ..., and Rest if ...

So you will have the same hvac_modes but with different name depend of the situation.

Or you can leave it like it is, it is not a big problem.

**Comment by thomasgermain** [comment]
Hi,

you can get the last version [here](https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2Fthomasgermain%2Fhome-assistant%2Ftree%2Fvaillant%2Fhomeassistant%2Fcomponents%2Fvaillant)

See doc for more information. The behavior is more based on what mobile apps provide.

Let me know if you have some troubles or suggestions.

Thomas

**Comment by Tomasonx** [comment]
Hi,

Yes this is "Cool" :)
No errors.
You can close this.

**Comment by Tomasonx** [comment]
When I change the desired temperature from [Auto 20 degree] to [ Cool 15 degree] I have "Cool mode".

But after 3 minutes or so it is come back to previous setup of 20 degree.

So is not working.
I see no errors.

**Comment by thomasgermain** [comment]
Ha dammed, I forgot the call the API when setting quick veto for a room.

You can download the last version.

**Comment by Tomasonx** [comment]
It works.
