### ISSUE TITLE
how to install ? 

### ISSUE THREAD

**Issue by rhgiter** [thomasgermain/pymultiMATIC#111]
hacs -> repositories

get this error <Integration thomasgermain/pymultiMATIC> Repository structure for 0.6.12 is not compliant

**Comment by thomasgermain** [comment]
Please check this repo: https://github.com/thomasgermain/vaillant-component/

**Comment by rhgiter** [comment]
yes, but its not working with senso app :-(     do you know where to find it for Sensoapp?

**Comment by thomasgermain** [comment]
This is the same repo. You have to check a check box to see the beta version. Then when configuring, you have to select sensoapp

**Comment by rhgiter** [comment]
ahh   thank you  :-)
