### ISSUE TITLE
FlowTemperatureVF1  - System flow temperature

### ISSUE THREAD

**Issue by kromosomX** [thomasgermain/pymultiMATIC#13]
My configuration reports the System flow temperature (in my case that is the temperature of the water flowing from the buffer to the underfloor heating circuits) on this URL:
/facilities/[SERIAL]/livereport/v1/devices/Control_SYS_MultiMatic/reports/FlowTemperatureVF1

In Vaillant Multimatic documentation this is referred as "SysFlow: System flow temperature", but in the 

Can you please add this to pymultiMATIC and the HA component when time permits.

It's grotesque how underutilized VR920 is. I have 7 temperature sensors (not counting the ones inside the heat pump and drinking water station!!)  integrated in my Vaillant system that I can read through the heat pump and VRC700, but only one is available via mobile apps. Ironicaly it's the one that is optional to install and doesn't have a real function (except for user info) in my configuration.

**Comment by thomasgermain** [comment]
Hi,

do you also have this one ? `FlowTemperatureSensor`
-> /facilities/[SERIAL]/livereport/v1/devices/Control_SYS_MultiMatic/reports/FlowTemperatureSensor

Do you also have the `sensor.vaillant_boiler_temperature` entity in HA ?

As far as I understand, `FlowTemperatureSensor` and `FlowTemperatureVF1` are the same thing, maybe the id depends on the type of device you have. So I could just check for one or the other to populate the value.

And yeah, I agree, they are missing a lot of information. I also have solar panels to heat hot water and I can get lof of data directly on the heater (energy produced, 2 temperature sensors, etc.), but I can't get anything from the API.

**Comment by kromosomX** [comment]
You are right that FlowTemperatureSensor and FlowTemperatureVF1 are probably the same thing, as I only have FlowTemperatureVF1, but not FlowTemperatureSensor. So just checking if one or the other is present would work OK.

I also have  sensor.vaillant_boiler_temperature in HA, but it's state is "unknown". 

Do you know about this https://github.com/john30/ebusd ? I experimented with it (you need an adapter) and I could get a lot of information from my system. With it you can read ANY data from VRC700 and VR71, so via that route I can get the value of most sensors in the system. The exception are the ones that are connected directly to the heat pump.

**Comment by thomasgermain** [comment]
I provide a fix in version 0.0.7. Could you do a test with the last version of the HA component ? You should get the correct value `sensor.vaillant_boiler_temperature`.

> Do you know about this https://github.com/john30/ebusd ? I experimented with it (you need an adapter) and I could get a lot of information from my system. With it you can read ANY data from VRC700 and VR71, so via that route I can get the value of most sensors in the system. The exception are the ones that are connected directly to the heat pump.

I had a look while looking for a solution to integrate vr920 inside vaillant. But it was a bit far from my confort zone. Do you made it working ?

**Comment by kromosomX** [comment]
Wow that was fast. Thank you!  sensor.vaillant_boiler_temperature now has a correct value!

With ebusd I just made initial connections as it takes some effort to configure it properly and I am constant lack of time. But I was able to get a lot of information out of it. I didn't have time to set up the MQTT connection between ebusd and Ha and  ebusd. And the ebusd component in HA is very limited and also it doesn't currently function with the wireles version of VRC700. So I decided that I'll use your component as a primary solution and only use ebusd for reading the missing values (most of the temperature sensors, states of mixing valves and water pumps, relative humidity ...). As there is no official protocol specification it is not easy to find the meaning of the messages or the relevant adresses for some of the data. But the support for the VRC units is almost complete and boilers are also supported quite well, but unfortunately not heat pumps.  I purchased a finished ebus adapter (https://www.esera.de/produkte/ebus/135/1-wire-hub-platine) and connected it via USB to raspberrry Pi. There is also an ethernet version of the adapter but as i've read it doesn't work well with ebusd because of the latency problems.

**Comment by thomasgermain** [comment]
Happy that it works :)

Thanks for your input and for ebusd.

**Comment by thomasgermain** [comment]
Sorry to bother you again, I just had a flash:
do you also have a correct value for the entity: `sensor.vaillant_boiler_pressure` ?

**Comment by kromosomX** [comment]
Yup. Boiler pressure worked from the start.
