### ISSUE TITLE
HA climate component for ZONES - day temperature field not populated correctly during night time

### ISSUE THREAD

**Issue by kromosomX** [thomasgermain/pymultiMATIC#16]
Hi, 

I only have zones in my configuration and there are multiple issues with the climate component for zones. I will rise them as separate issues so they can be individualy closed.  I updated to the latest version that uses pymultimatic 0.0.8. 

If I set AUTO mode via IOS app and DAY is scheduled both temperatures are read correctly (DAY/NIGH T) and two points appear on the arc), but if NIGHT is scheduled only the NIGHT temperature is read correctly and one dot appears and if you open the component both temperature fields are populated with NIGHT temperature.

**Comment by thomasgermain** [comment]
Hi,

could add a screenshot ?

Thanks,

Thomas

**Comment by kromosomX** [comment]
![image](https://user-images.githubusercontent.com/19895037/70330056-0689fe80-183d-11ea-9ac1-15cc137d468e.png)

ZGORAJ and SPODAJ have the same temperature settings for day and night. The only difference is that that SPODAJ is currently it day period and ZGORAJ in night period. Both set to AUTO mode

**Comment by thomasgermain** [comment]
Ok, I see, I guess you want to keep seeing 19.0 - 22.0 like SPODAJ ?

**Comment by kromosomX** [comment]
In current component behaviour that would make sense but first check the other issue where I am suggestting an alternative behaviour of the component. And this issue is obsolete if that route is taken.

**Comment by thomasgermain** [comment]
I'm closing this one in favor of #17
