### ISSUE TITLE
HA climate component for ZONES - different use of icons/modes - suggestion

### ISSUE THREAD

**Issue by kromosomX** [thomasgermain/pymultiMATIC#17]
I think it would be best if climate component mimics the App behaviour:
- if flame icon is pressed the DAY mode should start
- if snowflake icon is pressed the NIGHT mode should start (i think that COOL mode of the component could be used for NIGHT mode)
- only one temperature is shown in DAY/NIGHT mode (and if you change it you change the temperature of chosen mode)
- only one tempreature (DAY or NIGHT) is shown in AUTO mode appropriate to the current period
- if you change the temperature in AUTO mode Quick Veto is started 

What do you think about this behaviour? I think it covers all the modes that the VRC 700 does.

**Comment by thomasgermain** [comment]
I think this is a quite good idea.

I doesn't seems difficult to implement, but I have some work to do to keep the code consistent, I know what to do this week-end :yum:

**Comment by thomasgermain** [comment]
Hi,

I did some modification. It should fit what you suggest. This is available with the last version of the component [here](https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2Fthomasgermain%2Fhome-assistant%2Ftree%2Fvaillant%2Fhomeassistant%2Fcomponents%2Fvaillant)

Let me know if you have troubles or suggestions.

Thomas
