### ISSUE TITLE
typo in url for urls.emf_report_device

### ISSUE THREAD

**Issue by jecant** [thomasgermain/pymultiMATIC#22]
I created an url using the urls.emf_report_device, which resulted in the following string:

https://smart.vaillant.com/mobile/api/v4/facilities/{serial_number}/emf/v1/devices/{ID}?**energy_type**=CONSUMED_PRIMARY_ENERGY&function=CENTRAL_HEATING&timeRange=WEEK&start=2019-12-01&offset=2

However, it should be "energyType" instead of "energy_type to prevent getting the 400 error response.

**Comment by thomasgermain** [comment]
Hi, 

thanks for reporting. It should be fixed with version 0.0.11.

Could you confirm ?

Thanks,

Thomas

**Comment by jecant** [comment]
Fixed! Thanks a lot. Cheers, Jeroen
