### ISSUE TITLE
boiler temperature-> SysFlow

### ISSUE THREAD

**Issue by kromosomX** [thomasgermain/pymultiMATIC#27]
I suggest that you rename “boiler” to “SysFlow” or something similar because it’s configuration dependent. In my system it is showing the temperature of water flowing between the buffer and heating circuits. It isn’t showing the boiler (heat pump in my case) temperature. It is most obvious when it’s heating the domestic hot water, because it doesnt’ move at all.

I checked a few system diagrams of different Vaillant systems and some diagrams include SysFlow sensor (in systems with buffer it is positioned between buffer and heating circuits). Some diagrams don't include SysFlow sensor and I think that in those systems it is showing the boiler temperature.

**Comment by thomasgermain** [comment]
Hi,

thanks for posting the issue.

Do you also have the `WaterPressureSensor`, I guess this is also the pressure between the buffer and heating circuit ?

If the is the case, then I think I should rename boiler to sysflow (class `BoilerInfo` to `SysFlow`).

Now, I would like to figure out what is the real difference between `FlowTemperatureSensor` and `FlowTemperatureVF1`. Do you still have links about the diagram you're talking about ?

Will it be possible to receive the json for the call ?`https://smart.vaillant.com/mobile/api/v4/facilities/{serial}/livereport/v1` **Please ensure you anonymized some data like serial**

Thanks,

Thomas

**Comment by thomasgermain** [comment]
Hi,

I released a new version (pymultimatic and HA vaillant component) which now only get report from API data without trying to contextualize it
