### ISSUE TITLE
Estimate energy consumption

### ISSUE THREAD

**Issue by bcornelusse** [thomasgermain/pymultiMATIC#30]
Hello, 

I am wondering if there is a way to determine the energy consumed for heating. I think there is no directly available value from Vaillant, but do you think it is possible to estimate this through the circulation and water temperatures?

Note: I have a gas boiler and VR50 valves. I already use this module to record all room temperatures and setpoints, ... 

Thank you,
Bertrand.

**Comment by thomasgermain** [comment]
Hi Bertrand,

depending on your boiler/system you may have EMF. You could get data using `urls.emf_report_device`.

You have to provide your device id and parameters:

energyType:
– LIVE_DATA
– CONSUMED_PRIMARY_ENERGY
– CONSUMED_ELECTRICAL_POWER
– ENVIRONMENTAL_YIELD
– SOLAR_YIELD
– GRID_FEED_IN_ENERGY
– SELF_CONSUMED_ENERGY
– EARNED_PV_ENERGY

function:
– CENTRAL_HEATING
– DHW
– COOLING
– COMBINED
– PV

timeRange
– DAY
– WEEK
– MONTH
– YEAR

start:
– any date with format yyyy-MM-dd

offset
– checked the source code of the android apk and the only value I found is 6.


Maybe you can also check your boiler specs and based on the temperature you can maybe calculate consumption ?

Thomas

**Comment by bcornelusse** [comment]
Hi Thomas, thank you for your reply, and for your work.

I tried but It looks like EMF is not supported by my heating system (too old). 

And regarding the temperature, it looks that it measures only the temperature that leaves the boiler, not the return , so I am missing some information, I think it is going to be hard this way.

All the best, 
Bertrand.

**Comment by thomasgermain** [comment]
Maybe you can have a look at https://github.com/john30/ebusd/
I know some people are able to get a lot of information about boiler/water heater/etc from ebus
