### ISSUE TITLE
Multimaticweb

### ISSUE THREAD

**Issue by Commifreak** [thomasgermain/pymultiMATIC#33]
Hi @thomasgermain :)

I saw your code last year while I was searching for ways to collect data from my VR900. Since then I tried to build a web application which:

* Collects data from Vaillant Smart API
* Displays collected data as chart.

I reversed engineered the Android app using the latest version and found all Endpoints like yours and built a php based Data Harvester. Not all endpoints for me so I could not test everything. Thats the point I came to you today.

My application displays charts like:

![charts](https://user-images.githubusercontent.com/87267/77995046-58461f80-732b-11ea-9d74-20e88d1c4200.jpg)

Since I only have a normal HVAC in heating mode, I want to ask if you have a bigger setup with more data and if you would like to use the application. Or do you already built a solution on your own?

Regards!

![chart2](https://user-images.githubusercontent.com/87267/77995768-ad366580-732c-11ea-9cad-d536fe6a7dd5.jpg)
![modal1](https://user-images.githubusercontent.com/87267/77995770-adcefc00-732c-11ea-8c27-dabe3d5a2452.jpg)

**Comment by thomasgermain** [comment]
Hi Robin, 

this is quite an extensive work ! I checked your github, but I was not able to find the project, is it available ?

I would be happy to test your application and see the code :stuck_out_tongue: 

I'm currently using home assistant https://www.home-assistant.io/, which is actually doing also the same graph as you did, but It also allows automation and you can integrate multiple other equipment. I also develop an home assistant component (this is basically the link between home assistant and this project) in order to have all the data available in home assistant (here is the link https://github.com/thomasgermain/vaillant-component).

Cheerz,

Thomas

**Comment by Commifreak** [comment]
Unfortunately, no - I dont publushed the whole application. I could publish just the VaillantAPI-Component, but I dont feel that this is ready enough, though it works well. Maybe when I make the application productive.

To be honest: I still search for ways to get Base configuration data via VR900 by inspecting their VR900 <-> server communication which is not as easy than I thought.

Regards,

**Comment by thomasgermain** [comment]
What do you mean by base config ?

**Comment by Commifreak** [comment]
heating curve, flow target temperature, flow actual temperature.

This settings are only for maintenance technicians - or if you know the accesscode for this menu :)

**Comment by thomasgermain** [comment]
For me this is 000 but I guess it depends who created it :)

**Comment by Commifreak** [comment]
Exactly. But thats not the question. I want those datas in my chart as well ;)

**Comment by thomasgermain** [comment]
Maybe you can get some temperature from `https://smart.vaillant.com/mobile/api/v4/facilities/{serial_number}/livereport/v1`.

Even if the heating curve is available on vrc700, you won't be able to get it from the API.

**Comment by Commifreak** [comment]
I have these livereport values. I know, that these others are not in the API - I'll try to find a way to include them anyway. :)

**Comment by thomasgermain** [comment]
Hi Robin,

do you need more help or can I close the issue (or feel free to close it :) ).

Thanks,

Thomas

**Comment by Commifreak** [comment]
The class for API comms: https://gist.github.com/Commifreak/69a5f404db4de23b9fd7cef26e18ec61

Since I got blocked by vaillant (but released after asking), I give up the project. The data charts are nice but not that informative. eBUSd implementation allow much more things.

Maybe I publish the whole source of multimaticweb here.

**Comment by thomasgermain** [comment]
What do you mean by blocked ?

Why not creating a repo to store what you did ?

**Comment by Commifreak** [comment]
Blocked: Vaillant disabled my account because I called the api too often.

Repo: I did. But I seperated the Class before. I just created the repo: https://github.com/Commifreak/multimatic-web

Regards,
