### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by lecocqe** [thomasgermain/pymultiMATIC#36]
dear,

in the documentation, you speak "use pytest to run the tests", but after installing, i run pytest: "no such file".

best regards,

**Comment by thomasgermain** [comment]
Hello Eric,

you have to install `pytest` first: https://docs.pytest.org/en/stable/getting-started.html

Note that pytest is not required to make the project works (nor the HA component), this information is more for developers.

Regards,

Thomas

**Comment by lecocqe** [comment]
Hello Thomas,

ok, i understand. i'm trying to "play" with your code. but i need a first working example. because at the moment, I got "invalid syntax" at "connector" in "json = await connector.get(urls.facilities_list())"

from pymultimatic.api import Connector, urls

session = aiohttp.ClientSession
connector = Connector('user', 'pass', session)
json = await connector.get(urls.facilities_list()) 

regards,

Eric

**Comment by thomasgermain** [comment]
Hello, 

sorry for the late reply. The code moved to `async`. So you probably take a look at issue #43 I will update the doc with this example

**Comment by lecocqe** [comment]
Hello,

Just what is need.

Thx for this great job you made with this components.
