### ISSUE TITLE
is changing mode in set_zone_heating_operating_mode persistant?

### ISSUE THREAD

**Issue by h4de5** [thomasgermain/pymultiMATIC#41]
Hi,

this is not bug report, just maybe a stupid question - but I am currently trying to rule out a more substantial problem.

If you change the state (e.g. from heating to off, or from off to auto) using the `set_zone_heating_operating_mode` or even use the APP to change e.g. the floor heating mode - do you actually see a change in the current mode on the multimatic control panel? and does the setting stay like this?

because this is what I would expect - but for some reason the mode is reset after some minutes to what the multimatic was originally set to.

so if the multimatic is set to "day" mode - and I use the APP to change it to off, I immediately see the change in the HA entity, but like after 2-3 minutes it resets to "day" again. I tested it with almost all states combinations, even with HA shutdown and only using the vaillant APP - and it's always the same result.

so - not a bug report but a question (before I am contacting vaillant ..)

**Comment by h4de5** [comment]
I contacted vaillant. They wrote back today, saying they updated something. Works now...

**Comment by thomasgermain** [comment]
> I contacted vaillant. They wrote back today, saying they updated something. Works now...

How did you contact them ? Actually, I can't login to the API since monday... sent 10 mails, did 2 calls, but nothing is moving 😠

**Comment by h4de5** [comment]
contact form on their website: https://www.vaillant.at/privatanwender/kontakt/kontaktformular/

had a similar problem a while ago - they just disabled my account without any notice, because the username, which was created by their technician/support, was not an email address.

**Comment by thomasgermain** [comment]
oww actually my usernames are not email, i'm gonna check, thanks !
