### ISSUE TITLE
Ambisense valves ALWAYS ON

### ISSUE THREAD

**Issue by Tomasonx** [thomasgermain/pymultiMATIC#42]
Hi Thomas,

Maybe you know a solution...

You can setup an ambisense valve to different values or you can put the valve OFF.

My question is can I somehow put an ambisense valve always ON.

What do I mean.

Let's say I have 3 ambisense valves, 2 of which to work normally as before and one to stay always ON, like a bypass.
Each time one of the first 2 valves had started the heat to go to valve 3 also.

I know I can do this by removing the ambisense valve and using a normal valve that is permanently open, but I was wondering if it's not possible with the ambisense valve as well.

I know the short answer is NO, but you can think of a solution to this.

Thank you,

P.S.
You're doing a great job!

**Comment by thomasgermain** [comment]
Hi,

thanks for your inputs 😃 , really appreciated.

I didn't find any solution, I actually searched for the exact same use case (I have a  towel radiator in the bathroom and I would liked it to heat if any other first floor radiator is heating).

So yes, I think the only solution (I'm aware of) is to have a normal valve and let it open.

**Comment by Tomasonx** [comment]
Maybe Vaillant will read this.

Thank you
