### ISSUE TITLE
Module usage

### ISSUE THREAD

**Issue by Arendtsen** [thomasgermain/pymultiMATIC#43]
Hi

love the module in the earlier versions.
Now I have an issue when trying to use the example provided in the README.

When trying this:

# get the complete system
system = await manager.get_system()

I get this:
    system = await manager.get_system()
             ^
SyntaxError: 'await' outside function

What am I missing?

**Comment by thomasgermain** [comment]
Hello,

ah yeah sorry 😞 I forgot to update the documentation, you can check [this script](https://github.com/thomasgermain/pymultiMATIC/blob/master/script/dump.py) have a more concrete example.

Basically, you need to run the code inside the event loop, here is the an example (this will probably be the new example in the doc 😛)
```python3
#!/usr/bin/env python3
import asyncio
import sys

import aiohttp

from pymultimatic.systemmanager import SystemManager
from pymultimatic.model import System


async def main(user, passw):
    print('Trying to connect with user ' + user)

    async with aiohttp.ClientSession() as session:
        manager = SystemManager(user, passw, session)
        system =  await manager.get_system()
        print(system)



if __name__ == "__main__":
    if not len(sys.argv) == 3:
        print('Usage: python3 xxx.py user pass')
        sys.exit(0)
    user = sys.argv[1]
    passw = sys.argv[2]

    asyncio.get_event_loop().run_until_complete(main(user, passw))
```

Then you have to run the script like this:
`python3 your-script.py user password`

**Comment by Arendtsen** [comment]
Ah that makes sense - I wasn't too far away. :-D

Thanks!
