### ISSUE TITLE
Reports of Zone FlowTemperatur

### ISSUE THREAD

**Issue by h4de5** [thomasgermain/pymultiMATIC#45]
Hi,

is it possible to report the flowtemperatur of a zone? it seems I can only get the systems "vorlauf temperatur" which is higher than what the actual flowtemperature for the zone is:
api:

```
reports=[Report(id='FlowTemperatureVF1', value=33.8, name='Vorlauftemperatur VF1', unit='°C', device_id='Control_SYS_MultiMatic', device_name='multiMATIC') .. ]
```

on the multimatic:
![DSC_4158-cr](https://user-images.githubusercontent.com/6115324/99145188-fc879700-266c-11eb-9133-ffbb379bb5af.JPG)

if this is possible, it would be great to forward that status into HA as well!

best regards

**Comment by thomasgermain** [comment]
Hi,

You already have a entity with an id like this: `sensor.vaillant_flowtemperaturevf1` right ? (As far as I know, this is the hot water temperature)

Actually, most of the data in vrc700 are not in the API, so I can't get them included into HA. Does it appear on the mobile app ?

**Comment by h4de5** [comment]
Mmh. Hotwater i see. That would make sense. Even though i don't know when this information would be helpful?

Unfortunately no, it's not in the app either.

**Comment by thomasgermain** [comment]
If this is not in the app, I can't do anything about that unfortunately 😞 

> Mmh. Hotwater i see. That would make sense. Even though i don't know when this information would be helpful?

You mean the hotwater temperature  (sensor.vaillant_flowtemperaturevf1) ? This is used behind de the scene by the pymultimatic connector to have a complete hot water object (current temperature, time program, target temperature, etc.).

On HA level, all data coming from live reports are mapped to a sensor.

**Comment by h4de5** [comment]
I see. I had hoped to only activate the heat pump if a room thermostat is asking for heat and the flowtemperatur is below a certain value. But for this i would need that other sensor. 

Too bad :( 
Anyways thanks again for the rest help!
