### ISSUE TITLE
How would I find a list of issues in the API?

### ISSUE THREAD

**Issue by philippbosch** [thomasgermain/pymultiMATIC#47]
When using the multiMATIC iOS app, on the _Information_ tab there is a message at the top that currently reads `Das System läuft ohne Probleme` (🇩🇪, roughly: The system does not have any issues). When there is an issue the text is different and there's an overlay with a list of issues if I recall correctly. Where in the API would I find this status and/or the current issues? 

I've checked out https://github.com/thomasgermain/pymultiMATIC/blob/97b7dbe349c931a1f949f4a20b35693820473032/pymultimatic/api/urls.py#L332 and https://github.com/thomasgermain/pymultiMATIC/blob/97b7dbe349c931a1f949f4a20b35693820473032/pymultimatic/api/urls.py#L297 but I can't find anything there. This could be because I'm blind or stupid or both, or because there aren't any issues at the moment. Could you give me a hint in the right direction where to find these issues?

Thanks for your help!

**Comment by thomasgermain** [comment]
You should check `urls.hvac` to find any error. But apparently, not all devices support the error report.

You could check this test file: https://github.com/thomasgermain/pymultiMATIC/blob/master/tests/files/responses/hvacstate_errors

This is an example of response of the API. (First message is not an error, see `type` = `STATUS`, but the second one is an error).

**Comment by philippbosch** [comment]
Thanks for your quick response, @thomasgermain!

Unfortunately the response body of an `hvav()` call is empty for me:

```json
{
  "body": {},
  "meta": {
    "onlineStatus": {
      "status": "ONLINE"
    },
    "firmwareUpdateStatus": {
      "status": "UPDATE_NOT_PENDING"
    },
    "syncState": [
      {
        "state": "SYNCED",
        "timestamp": 1608032579875,
        "link": {
          "rel": "self",
          "resourceLink": "/facilities/…/hvacstate/v1/overview"
        }
      }
    ]
  }
}
```

A call to `hvac_update()` doesn't change that. 

I'll keep digging.

**Comment by thomasgermain** [comment]
Yes, this is what I said earlier, some devices are not reporting any state or error. Maybe you can try to stop your boiler or heat pump. Normally you should receive an error about ebus connection

**Comment by thomasgermain** [comment]
Hi @philippbosch do you need more support about this issue ? Otherwise, I'm gonna close it :)

**Comment by philippbosch** [comment]
Well, I haven't found a way to get a list of issues. But this is very likely not an issue with your library. So I'll close this for now and will report back when I find a solution. Thanks for your help!
