### ISSUE TITLE
Don't require WiFi MAC

### ISSUE THREAD

**Issue by dupondje** [thomasgermain/pymultiMATIC#68]
Hi,

I have a VR900, but it does not work with Home Assistant.
Logs give me:
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 738, in _validate_schema
    return schema.validate(response)
  File "/opt/homeassistant/lib/python3.8/site-packages/schema.py", line 400, in validate
    raise SchemaError([message] + x.autos, [e.format(data) if e else None] + x.errors)
schema.SchemaError: Key 'body' error:
Key 'facilitiesList' error:
Or({'serialNumber': And(<class 'str'>, <built-in function len>), 'name': And(<class 'str'>, <built-in function len>), 'responsibleCountryCode': And(<class 'str'>, <built-in function len>), 'supportedBrand': And(<class 'str'>, <built-in function len>), 'firmwareVersion': And(<class 'str'>, <built-in function len>), 'capabilities': [And(<class 'str'>, <built-in function len>)], 'networkInformation': {'macAddressEthernet': And(<class 'str'>, <built-in function len>), 'macAddressWifiAccessPoint': And(<class 'str'>, <built-in function len>), 'macAddressWifiClient': And(<class 'str'>, <built-in function len>)}}) did not validate {'serialNumber': 'xxxx', 'name': 'xxxxx', 'responsibleCountryCode': 'BE', 'supportedBrand': 'GREEN_BRAND_COMPATIBLE', 'capabilities': ['SYSTEMCONTROL_MULTIMATIC'], 'networkInformation': {'macAddressEthernet': 'xxxx:f6'}, 'firmwareVersion': '331.20.7'}
Key 'networkInformation' error:
Missing keys: 'macAddressWifiAccessPoint', 'macAddressWifiClient'

But as the VR900 does not have a Wifi built-in, its normal that this data is missing.

Can this be fixed?

Thanks!

**Comment by thomasgermain** [comment]
Hello,

well spotted, this will be included in the next release
