### ISSUE TITLE
Missing key: 'timeprogram'

### ISSUE THREAD

**Issue by dupondje** [thomasgermain/pymultiMATIC#70]
Hi,

Seems like some more things don't work on a VR900 :)

schema.SchemaError: Key 'dhw' error:
Or({'_id': And(<class 'str'>, <built-in function len>), 'hotwater': Schema({'configuration': {Or('mode', 'operation_mode', 'operationMode'): And(<class 'str'>, <built-in function len>), Optional(Or('setpoint_temperature', 'temperature_setpoint', 'temperatureSetpoint', 'day_level')): Or(<class 'int'>, <class 'float'>), Optional(Or('setback_temperature', 'night_level')): Or(<class 'int'>, <class 'float'>), Optional('day_level'): <class 'int'>, Optional('night_level'): <class 'int'>}, 'timeprogram': Schema({'monday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'tuesday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'wednesday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'thursday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'friday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'saturday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'sunday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}]})}), 'circulation': Schema({'configuration': {Or('mode', 'operation_mode', 'operationMode'): And(<class 'str'>, <built-in function len>), Optional(Or('setpoint_temperature', 'temperature_setpoint', 'temperatureSetpoint', 'day_level')): Or(<class 'int'>, <class 'float'>), Optional(Or('setback_temperature', 'night_level')): Or(<class 'int'>, <class 'float'>), Optional('day_level'): <class 'int'>, Optional('night_level'): <class 'int'>}, 'timeprogram': Schema({'monday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'tuesday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'wednesday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'thursday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'friday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'saturday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}], 'sunday': [{'startTime': And(<class 'str'>, <built-in function len>), Optional('temperatureSetpoint'): Or(<class 'int'>, <class 'float'>), Optional('setting'): And(<class 'str'>, <built-in function len>), Optional('mode'): And(<class 'str'>, <built-in function len>)}]})}), Optional('controlled_by'): Schema({'name': And(And(<class 'str'>, <built-in function len>), <function <lambda> at 0x7fe4cc567b80>), Optional('link'): {Optional('rel'): <class 'str'>, 'resourceLink': <class 'str'>, Optional('name'): <class 'str'>}})}) did not validate {'hotwater': {'configuration': {'operation_mode': 'AUTO', 'temperature_setpoint': 60.0}}, 'circulation': {'configuration': {'operationMode': 'AUTO'}}, '_id': 'Control_DHW'}
Key 'hotwater' error:
Missing key: 'timeprogram'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 738, in _validate_schema
    return schema.validate(response)
  File "/opt/homeassistant/lib/python3.8/site-packages/schema.py", line 400, in validate
    raise SchemaError([message] + x.autos, [e.format(data) if e else None] + x.errors)
schema.SchemaError: Key 'body' error:

Fixed this by setting the FUNCTION_PART's timeprogram to Optional()

**Comment by thomasgermain** [comment]
do you have hotwater ?
