### ISSUE TITLE
Vaillant Multimatic Remote Restart command

### ISSUE THREAD

**Issue by Krzysztonek** [thomasgermain/pymultiMATIC#86]
Dear @thomasgermain
Sometimes, for some reason, my Vaillant hangs with some minor error on its display.
To remove such an error I have to go down to the laundry (where my Vaillant is located), and physically press the button on the display to reset the device. I wonder if there is any chance to send RESET or RESTART command remotely from Home Assistant.
Would you please advise me on that topic?

**Comment by thomasgermain** [comment]
Hello,

I just had a look, but here is no way to restart the gateway :/

**Comment by Krzysztonek** [comment]
May I assume that this function/command would be implemented in the future?
For now: is it possible to reset the device by turning its power off for a while and then turning it on back?
Thank you for or clarification, @thomasgermain  ☕

**Comment by thomasgermain** [comment]
I cannot implement it myself, so it should come from vaillant team.
I don't think such functionality will be implemented, but I know that multimatic application will be replaced by myVaillant application (and so the API will change). So maybe there will be a way to restart it.

**Comment by tpires** [comment]
Hi @thomasgermain. do you have any idea if it will be possible to use the API for the new app? since September the app and API have been unusable, a lot of errors for auth and any command.
