### ISSUE TITLE
Water pressure + Flow temperature + Control time

### ISSUE THREAD

**Issue by Tomasonx** [thomasgermain/pymultiMATIC#9]
I have an VR 920 + VRC 700 / 5 + VR 50

**1. In this picture**

![Pression chaudiere 1.4 bar](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/9/4/94110001fdd454e59768403bdba747de0b43e432.png)

you have "Pression chaudiere 1.4 bar"

I can see this information on the VRC 700 app but not on home-assistant
[**thomasgermain**/home-assistant/homeassistant/components/vaillant/](https://github.com/thomasgermain/home-assistant/tree/vaillant/homeassistant/components/vaillant)

Can you check this?

I will attach a print screen.

**2. In the same print screen you can see "Flow temperature sensor"**
Can you add that too?

My print screen
![2019-11-22](https://user-images.githubusercontent.com/11645510/69413599-6ba80500-0d11-11ea-914e-4f1526b42377.jpeg)

**Comment by thomasgermain** [comment]
Hi,

Any error in the log ?

The entity id should be something like: `sensor.vaillant_vc_be_246_5_3_pressure` and `sensor.vaillant_vc_be_246_5_3_temperature` where `vc_be_246_5_3` is the version of my boiler, so it may differ for your entities id.

Thomas

**Comment by Tomasonx** [comment]
No errors and I no similar ID

**Comment by thomasgermain** [comment]
Hmm, it seems like it's coming from the data from the API (I guess they are not formatted like I received mine).

The warning is not related to the vaillant component.

May I ask you to run some python script to check how data are coming for you ? So I can check where the problem is. (I still have to prepare the script)

**Comment by Tomasonx** [comment]
OK, no problem

**Comment by Tomasonx** [comment]
And maybe "Control time and date" from the VRC 700 app on Settings / General Settings

Can you extract this value to see when the information was updated?

**Comment by thomasgermain** [comment]
> And maybe "Control time and date" from the VRC 700 app on Settings / General Settings
> 
> Can you extract this value to see when the information was updated?

Is it what you're looking for ?

![image](https://user-images.githubusercontent.com/12560542/69420071-381fa780-0d1e-11ea-9575-a059df9f2a80.png)

This is the time the boiler status was updated. This is a state attribute of the status of the boiler, but maybe you don't have the entity neither ?

**Comment by Tomasonx** [comment]
Yes I think this is it.
And yes I do not have this.

**Comment by Tomasonx** [comment]
So you have VC BE 246/5-3
I have VUW BE 240/3-5

**Comment by thomasgermain** [comment]
So, here is the script: https://github.com/thomasgermain/pymultiMATIC/blob/issue9/data_from_vaillant.py

you can download it and run:
```python
python3 data_from_vaillant.py username password
```
It will print some json data I would need to add support for your boiler. There is no real private data here, but you can remove your facility number in `resourceLink`

Thanks,

Thomas

**Comment by Tomasonx** [comment]
I run homeassistant on raspberrypi3 on docker

I put in

homeassistant/custom_components

the vaillant directory from here
[https://github.com/thomasgermain/home-assistant/homeassistant/components/vaillant/](https://github.com/thomasgermain/home-assistant/tree/vaillant/homeassistant/components/vaillant)


so when i run data_from_vaillant.py I have the next error

`Traceback (most recent call last):`
`  File "data_from_vaillant.py", line 4, in <module>`
`    from pymultimatic.api import ApiConnector, urls`
`ModuleNotFoundError: No module named 'pymultimatic'`

**Comment by thomasgermain** [comment]
Ah yeah sorry. You can actually run the script everywhere you want, but you need to install pymultimatic dependency before running the script:

`sudo pip3 install pymultimatic`

**Comment by Tomasonx** [comment]
And now:


Traceback (most recent call last):
  File "data_from_vaillant.py", line 4, in <module>
    from pymultimatic.api import ApiConnector, urls
  File "/usr/local/lib/python3.7/dist-packages/pymultimatic/api/__init__.py", line 3, in <module>
    from .error import ApiError
  File "/usr/local/lib/python3.7/dist-packages/pymultimatic/api/error.py", line 6, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'

**Comment by Tomasonx** [comment]
I fix this and now I have
--------------


2019-11-00 00:00:00,000:INFO:Connector: No previous session found, will try to log in with username: ABC and smartphoneId: pymultiMATIC
{'body': {'devices': [{'reports': [{'unit': '°C', 'name': 'Cylinder hot water temperature', 'value': 14.0, '_id': 'DomesticHotWaterTankTemperature', 'measurement_category': 'TEMPERATURE', 'associated_device_function': 'DHW'}], '_id': 'Control_DHW', 'name': 'Domestic hot water circuit'}, {'reports': [{'unit': 'bar', 'name': 'Water pressure', 'value': 1.3, '_id': 'WaterPressureSensor', 'measurement_category': 'PRESSURE', 'associated_device_function': 'HEATING'}], '_id': 'Control_SYS_MultiMatic', 'name': 'VRC 700/5'}, {'reports': [{'unit': '°C', 'name': 'Flow temperature sensor', 'value': 15.0, '_id': 'FlowTemperatureSensor', 'measurement_category': 'TEMPERATURE', 'associated_device_function': 'HEATING'}], '_id': 'Control_CC1', 'name': 'Heating circuit 1'}]}, 'meta': {'resourceState': [{'state': 'SYNCED', 'timestamp': 0, 'link': {'rel': 'child', 'resourceLink': '/facilities/ABC/livereport/v1/devices/Control_DHW/reports/DomesticHotWaterTankTemperature'}}, {'state': 'SYNCED', 'timestamp': 0, 'link': {'rel': 'child', 'resourceLink': '/facilities/ABC/livereport/v1/devices/Control_SYS_MultiMatic/reports/WaterPressureSensor'}}, {'state': 'SYNCED', 'timestamp': 0, 'link': {'rel': 'child', 'resourceLink': '/facilities/ABC/livereport/v1/devices/Control_CC1/reports/FlowTemperatureSensor'}}]}}



{'body': {}, 'meta': {'onlineStatus': {'status': 'ONLINE'}, 'firmwareUpdateStatus': {'status': 'UPDATE_NOT_PENDING'}, 'syncState': [{'state': 'SYNCED', 'timestamp': 0, 'link': {'rel': 'self', 'resourceLink': '/facilities/ABC/hvacstate/v1/overview'}}]}}


-------------

**Comment by thomasgermain** [comment]
So, I spot the problem. I'm currently busy with a fix for `pymultimatic` module. Then I will adapt vaillant component.

The thing is, you will be able to get temperature and pressure of the boiler only. Apparently your boiler is not able to provide hvac information (model of the boiler, current mode, last update, etc.)

**Comment by thomasgermain** [comment]
Could you try the last version of the component ?

You should be able to get pressure and temperature for the boiler with entity ` sensor.vaillant_boiler_pressure` and ` sensor.vaillant_boiler_temperature`.

Let me know if there is any issue

**Comment by Tomasonx** [comment]
It is working, no errors.

Of course do you know that I changed:
timestamp: 0
/facilities/2xxxxxxxx = /facilities/ABC



And "Control time and date"?

**Comment by thomasgermain** [comment]
Cool great :)

Could you show me in the app what is the "Control time and date" ?
From what I think, it's just the date and time of the boiler, this is not the last update. In the multimatic app, this field is editable.

I think I cannot provide you the last update since there is no hvac information from your boiler (I mean the `body` is empty).

**Comment by Tomasonx** [comment]
Go to Settings / General settings / 

there you have "Time" (the actual time)
and "Control time and date" (last update time)
and of course after a few seconds Time = Control time and date






![1](https://user-images.githubusercontent.com/11645510/69475769-948fcf00-0dd1-11ea-9136-b86b322f2191.jpg)
![2](https://user-images.githubusercontent.com/11645510/69475773-9b1e4680-0dd1-11ea-9aeb-6c96af8d95f2.jpg)
![3](https://user-images.githubusercontent.com/11645510/69476036-ed149b80-0dd4-11ea-9545-4716e71e3f3d.jpg)

**Comment by thomasgermain** [comment]
ah you're from Belgium too :)

The time displayed here is actually the current time coming from the API. Since the mobile app is quite slow to update, than you can notice a gap between the current time and time displayed in the field.

Honestly, I cannot find any interest of displaying that in HA. What could be your use case ?

**Comment by Tomasonx** [comment]
Yes .be,

My idea was to have a value, 10 degree from outdoor sensor, and a time to know how old is that value.

So => 10 degree 6 minutes ago

**Comment by thomasgermain** [comment]
Here is what you can get with HA:

![image](https://user-images.githubusercontent.com/12560542/69479553-cec39580-0dfe-11ea-8d1e-74050682a6dc.png)

**Comment by Tomasonx** [comment]
I don't know how is this working.

How I understand 10 minutes from your print screen represents how long the temperature was 8.0 degree.

In my print screen I have 8 degree from 3:44 to 4:45 so 1 h


![1](https://user-images.githubusercontent.com/11645510/69481465-e8220d00-0e11-11ea-97e3-5636892ac996.PNG)
![2](https://user-images.githubusercontent.com/11645510/69481468-ebb59400-0e11-11ea-8c89-75d53c4c7924.PNG)


The problem is when (most often on weekends) I can't get data in the app, because the Vaillant server is down or something.

If I understand correctly you take the data from the Vaillant server and not directly from boiler / VR 920 / VRC 700 / VR 50 (like the app). 
If this is right will be interesting to know how old are data.


But, how this is working on HA is perfect enough, at least for me.
You did a good job :)

**Comment by thomasgermain** [comment]
Thanks :)

You're right with your interpretation of how home assistant works.

And you're right, i'm getting data from server (like the application does). Meaning, if  your HA instance doesn't have internet access, you won't get any data from vaillant server.

I think the problem is coming from your outdoor sensor. I already had some complaints about the accuracy of the data, but I can only read what is coming from vaillant server.

You can also change the `scan_interval`. By default it's 5 minutes, meaning HA will fetch data every 5 minutes. You can set like this:

```yaml
vaillant:
  username: xxxx
  password: xxx
  scan_interval: 
    minutes: 1
```

Should I considered it close ?

Anyway, let me know if you have any errors/questions/suggestions :)

**Comment by Tomasonx** [comment]
No errors/questions/suggestions.



Thank you!
