### ISSUE TITLE
Map all hvac state error messages

### ISSUE THREAD

**Issue by thomasgermain** [thomasgermain/pymultiMATIC#90]
Map all hvac state error messages from the API and not only them with `type` = `ERROR`

**Comment by caroso-de** [comment]
i think this is related to https://github.com/thomasgermain/vaillant-component/issues/147?

I checked out the patch against my current problem and its working fine

**Comment by thomasgermain** [comment]
Yes, this is related ;) 

I need first to change the way I grab error messages from the API here, so HA can have it available
