### ISSUE TITLE
User-Agent header field now required

### ISSUE THREAD

**Issue by obiltschnig** [thomasgermain/pymultiMATIC#97]
Not sure if it affects `pymultiMATIC`, but I just noticed with my own implementation that as of 10:30 today, the Vaillant API expects to see a `User-Agent` header in API requests, otherwise a 500 error is returned. The value of the `User-Agent` does not seem to matter, but it's probably worth keeping an eye on it.

**Comment by lnowakowski** [comment]
It has been already included and fixed in #95

**Comment by thomasgermain** [comment]
Hello,

Thanks for the tip :)

For now, it still work, but I had to add a `Vaillant-Mobile-App` header ~a month ago to make it work again

**Comment by obiltschnig** [comment]
It looks like `pymultiMATIC` client is not affected by it as the `User-Agent` header is added automatically by the Python HTTP client.
